//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlmonFuncTestNunit.Scripts {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScriptsJS {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScriptsJS() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlmonFuncTestNunit.Scripts.ScriptsJS", typeof(ScriptsJS).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var elements = document.querySelector(&quot;div[data-role=calendar] td[class~=k-today] a&quot;);
        ///elements.click();.
        /// </summary>
        internal static string calendar {
            get {
                return ResourceManager.GetString("calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to document.getElementById(&quot;DataGrid1_ctl52_lblWorkflowName&quot;).scrollIntoView();.
        /// </summary>
        internal static string calendarCheckScrollDown {
            get {
                return ResourceManager.GetString("calendarCheckScrollDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to document.getElementById(&quot;DataGrid1_ctl23_lblWorkflowName&quot;).scrollIntoView();.
        /// </summary>
        internal static string calendarCheckScrollJustify {
            get {
                return ResourceManager.GetString("calendarCheckScrollJustify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var el =document.querySelector(&apos;#DataGrid1 &gt; tbody &gt; tr.TableHeader &gt; td:nth-child(1) &gt; a&apos;);
        ///el.scrollIntoView();
        ///el.click();.
        /// </summary>
        internal static string calendarCheckScrollUp {
            get {
                return ResourceManager.GetString("calendarCheckScrollUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var elements = [].slice.call(document.querySelectorAll(&quot;span[class~=rtPlus]&quot;));
        ///elements[17].click();.
        /// </summary>
        internal static string cparrowsAiPlugin {
            get {
                return ResourceManager.GetString("cparrowsAiPlugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var elements = [].slice.call(document.querySelectorAll(&quot;span[class~=rtPlus]&quot;));
        ///elements[9].click();.
        /// </summary>
        internal static string cparrowsBoL {
            get {
                return ResourceManager.GetString("cparrowsBoL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var elements = [].slice.call(document.querySelectorAll(&quot;span[class~=rtPlus]&quot;));
        ///elements[15].click();.
        /// </summary>
        internal static string cparrowsCalendar {
            get {
                return ResourceManager.GetString("cparrowsCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var elements = [].slice.call(document.querySelectorAll(&quot;span[class~=rtPlus]&quot;));
        ///elements[8].click();.
        /// </summary>
        internal static string cparrowsCare {
            get {
                return ResourceManager.GetString("cparrowsCare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var elements = [].slice.call(document.querySelectorAll(&quot;span[class~=rtPlus]&quot;));
        ///elements[6].click();.
        /// </summary>
        internal static string cparrowsColorValidTables {
            get {
                return ResourceManager.GetString("cparrowsColorValidTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var elements = [].slice.call(document.querySelectorAll(&quot;span[class~=rtPlus]&quot;));
        ///elements[11].click();.
        /// </summary>
        internal static string cparrowsFlashCosting {
            get {
                return ResourceManager.GetString("cparrowsFlashCosting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var elements = [].slice.call(document.querySelectorAll(&quot;span[class~=rtPlus]&quot;));
        ///elements[7].click();.
        /// </summary>
        internal static string cparrowsGenValTables {
            get {
                return ResourceManager.GetString("cparrowsGenValTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var elements = [].slice.call(document.querySelectorAll(&quot;span[class~=rtPlus]&quot;));
        ///elements[5].click();.
        /// </summary>
        internal static string cparrowsImgValTables {
            get {
                return ResourceManager.GetString("cparrowsImgValTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var elements = [].slice.call(document.querySelectorAll(&quot;span[class~=rtPlus]&quot;));
        ///elements[10].click();.
        /// </summary>
        internal static string cparrowsLineList {
            get {
                return ResourceManager.GetString("cparrowsLineList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var elements = [].slice.call(document.querySelectorAll(&quot;span[class~=rtPlus]&quot;));
        ///elements[3].click();.
        /// </summary>
        internal static string cparrowsMatSubTypes {
            get {
                return ResourceManager.GetString("cparrowsMatSubTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var elements = [].slice.call(document.querySelectorAll(&quot;span[class~=rtPlus]&quot;));
        ///elements[4].click();.
        /// </summary>
        internal static string cparrowsMatValTables {
            get {
                return ResourceManager.GetString("cparrowsMatValTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var elements = [].slice.call(document.querySelectorAll(&quot;span[class~=rtPlus]&quot;));
        ///elements[2].click();.
        /// </summary>
        internal static string cparrowsMeasurements {
            get {
                return ResourceManager.GetString("cparrowsMeasurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var elements = [].slice.call(document.querySelectorAll(&quot;span[class~=rtPlus]&quot;));
        ///elements[13].click();.
        /// </summary>
        internal static string cparrowsPartnerFolder {
            get {
                return ResourceManager.GetString("cparrowsPartnerFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var elements = [].slice.call(document.querySelectorAll(&quot;span[class~=rtPlus]&quot;));
        ///elements[14].click();.
        /// </summary>
        internal static string cparrowsPlanningFolder {
            get {
                return ResourceManager.GetString("cparrowsPlanningFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var elements = [].slice.call(document.querySelectorAll(&quot;span[class~=rtPlus]&quot;));
        ///elements[12].click();.
        /// </summary>
        internal static string cparrowsSourcingFolder {
            get {
                return ResourceManager.GetString("cparrowsSourcingFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var elements = [].slice.call(document.querySelectorAll(&quot;span[class~=rtPlus]&quot;));
        ///elements[16].click();.
        /// </summary>
        internal static string cparrowsTechPacks {
            get {
                return ResourceManager.GetString("cparrowsTechPacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var elements = [].slice.call(document.querySelectorAll(&quot;span[class~=rtPlus]&quot;));
        ///elements[1].click();.
        /// </summary>
        internal static string cparrowsTemplates {
            get {
                return ResourceManager.GetString("cparrowsTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var elements = [].slice.call(document.querySelectorAll(&quot;span[class~=rtPlus]&quot;));
        ///elements[0].click();.
        /// </summary>
        internal static string cparrowsWorkflows {
            get {
                return ResourceManager.GetString("cparrowsWorkflows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var minus = document.querySelector(&quot;#LeftMenu_ControlLeftMenuYSTreeView1 &gt; ul &gt; li &gt; ul &gt; li &gt; div &gt; span.rtMinus&quot;);
        ///minus.click();.
        /// </summary>
        internal static string cpMinus {
            get {
                return ResourceManager.GetString("cpMinus", resourceCulture);
            }
        }
    }
}
